# Generated by Django 5.0.6 on 2024-05-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='Ataque',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='carta',
            name='Costo',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='carta',
            name='Defensa',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='CantCirculo',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='CantCuadrado',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='CantTriangulo',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='PartidasGanadas',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='PartidasPerdidas',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='PartidasTotales',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='ScoreTotal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partidajugador',
            name='ScoreGanado',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='partidajugador',
            name='VidaRestante',
            field=models.SmallIntegerField(),
        ),
    ]
