# Generated by Django 5.0.4 on 2024-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_alter_carta_ataque_alter_carta_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidajugador',
            name='VidaRestante',
        ),
        migrations.AlterField(
            model_name='carta',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='cartas/'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='imagenTipo',
            field=models.ImageField(blank=True, upload_to='tipes/'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='BackImage',
            field=models.ImageField(blank=True, upload_to='backimages/'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='FotoPerfil',
            field=models.ImageField(blank=True, upload_to='perfilimages/'),
        ),
    ]
