# Generated by Django 5.0.4 on 2024-05-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0003_remove_partidajugador_vidarestante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='PuntosRestantes',
            field=models.IntegerField(default=100),
        ),
    ]
