# Generated by Django 5.0.4 on 2024-05-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0004_deck_puntosrestantes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jugador',
            managers=[
            ],
        ),
    ]
