# Generated by Django 5.0.4 on 2024-06-05 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0006_alter_jugador_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='Tipo',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='Cartas',
        ),
        migrations.AlterField(
            model_name='deck',
            name='CantCirculo',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='CantCuadrado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='CantTriangulo',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='PartidasGanadas',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='PartidasPerdidas',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='PartidasTotales',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ci', 'Circulo'), ('cu', 'Cuadrado'), ('tr', 'Triangulo')], max_length=2)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.carta')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logica.deck')),
            ],
            options={
                'unique_together': {('deck', 'carta', 'tipo')},
            },
        ),
    ]
