# Generated by Django 5.0.4 on 2024-06-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0008_rename_puntosrestantes_deck_puntos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deckcard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carta',
            name='imagenTipo',
        ),
        migrations.AddField(
            model_name='deckcard',
            name='imagenTipo',
            field=models.ImageField(blank=True, upload_to='tipes/'),
        ),
    ]
