# Generated by Django 5.0.4 on 2024-06-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0009_alter_deckcard_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='deck_seleccionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugador_seleccionado', to='logica.deck'),
        ),
    ]
