# Generated by Django 5.2.dev20240617101926 on 2024-06-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0009_alter_deckcard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='BackImage',
            field=models.ImageField(blank=True, upload_to='backim/'),
        ),
    ]
