# Generated by Django 5.2.dev20240617101926 on 2024-06-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0010_alter_deck_backimage'),
        ('logica', '0010_jugador_deck_seleccionado'),
    ]

    operations = [
    ]
