# Generated by Django 5.0.4 on 2024-06-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0011_merge_20240619_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='PartidasGanadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='PartidasPerdidas',
            field=models.IntegerField(default=0),
        ),
    ]
