# Generated by Django 5.0.4 on 2024-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0013_alter_partida_tiempojugado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='TiempoJugado',
            field=models.DateField(),
        ),
    ]
